### ISSUE TITLE
Error when trying to run on MacOS

### ISSUE THREAD

**Issue by andresobral** [denoland/deno_install#1]
I tryied to run the installer on my mac and I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 92, in <module>
  File "<stdin>", line 53, in main
  File "<stdin>", line 38, in release_url
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
```

MacOS version: 10.12.6
Python version: 2.7.10

**Comment by DanielSokil** [comment]
@andresobral 
```bash
$ brew install openssl
$ brew link --force openssl
$ brew install python --with-brewed-openssl
```

**Comment by MarkTiedemann** [comment]
Since #42, the python installer is deprecated. So this issue can be closed.

cc @ry
