### ISSUE TITLE
colors.ts 404 not found

### ISSUE THREAD

**Issue by Fer17** [denoland/deno_install#111]
Running my Deno project with **deno -A index.js**, I've got a

Download https://deno.land/std@v0.17.0/fmt/colors.ts
error: Uncaught Error: Import 'https://deno.land/std@v0.17.0/fmt/colors.ts' failed: 404 Not Found
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async processImports ($deno$/compiler/imports.ts:148:23)
    at async processImports ($deno$/compiler/imports.ts:156:7)
    at async processImports ($deno$/compiler/imports.ts:156:7)
    at async processImports ($deno$/compiler/imports.ts:156:7)
    at async processImports ($deno$/compiler/imports.ts:156:7)
    at async processImports ($deno$/compiler/imports.ts:156:7)
    at async processImports ($deno$/compiler/imports.ts:156:7)
    at async Object.processImports ($deno$/compiler/imports.ts:156:7)

I've checked it and, of course, it doesn't exist.

The rest of downloads are OK.

deno --version
deno 0.42.0
v8 8.2.308
typescript 3.8.3

Thank you in advance.

**Comment by MarkTiedemann** [comment]
Hi @Fer17, I think `std@0.17.0` is no longer available (I'm not sure why). In any case, the oldest version that is still available via deno.land is `0.34.0`: https://deno.land/std@0.34.0/fmt/colors.ts The newest version of `colors.ts` is `0.50.0`: https://deno.land/std@0.50.0/fmt/colors.ts Hope this helps.

**Comment by MarkTiedemann** [comment]
Not really a `deno_install` issue any way.

@bartlomieju Wanna move or close?

**Comment by bartlomieju** [comment]
@Fer17 please update to latest Deno version and use `std@0.53.0` for standard library imports. If you face any more trouble please open issue in main repo

**Comment by Fer17** [comment]
Thank you all. Sorry for my delay answering you back: busy days. After your hints (and more training on how  Deno works), everything it's ok.
